---
# Rancher tasks

- name: Add Rancher Helm repository
  kubernetes.core.helm_repository:
    name: rancher-alpha
    repo_url: https://releases.rancher.com/server-charts/alpha
    state: present  # Ensure the repository is added
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Create Rancher namespace
  kubernetes.core.k8s:
    name: cattle-system
    api_version: v1
    kind: Namespace
    state: present  # Ensure the namespace exists
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true  # Update the Helm repo cache
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Add Rancher Helm repository
  shell: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  tags: [rancher_dashboard]

- name: Deploy Rancher chart inside cattle-system namespace
  kubernetes.core.helm:
    name: rancher
    chart_ref: "{{ rancher_chart_ref }}"
    chart_version: "{{ rancher_chart_version }}"
    release_namespace: cattle-system
    create_namespace: true
    update_repo_cache: true
    state: present
    wait: true
    values:
      ingress:
        tls:
          source: "none"
      bootstrapPassword: admin
      hostname: "{{ hostname }}"  # Set the Rancher hostname
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable


# - name: Install Rancher via Helm
#   shell: |
#     export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
#     helm install rancher rancher-stable/rancher \
#       --namespace cattle-system \
#       --create-namespace \
#       --set hostname={{ hostname }} \
#       --set bootstrapPassword=admin \
#       --set ingress.tls.source=none \
#   tags: [rancher_dashboard]