---
# Ansible Common Variables
home_path: /home/adminuser
ssh_user: adminuser
ansible_sudo_pass: adminpass
ssh_cert: ~/.ssh/id_ed25519
ssh_port: "22"
server_agent_1: "192.168.0.26"
server_agent_2: "192.168.0.29"
server_agent_3: "192.168.0.24"
worker_agent_1: "192.168.0.27"
TZ: America/Toronto

# Kubernetes
kubectl_config: "/etc/rancher/rke2/rke2.yaml"
helm_version: v3.15.1 # https://github.com/helm/helm/releases

# cert-manager
cert_manager_chart_ref: jetstack/cert-manager
cert_manager_chart_version: v1.15.0 # https://github.com/cert-manager/cert-manager/releases
cert_manager_email: "your-email@gmail.com"

# Rancher
rancher_chart_ref: rancher-stable/rancher
rancher_chart_version: v2.10.2 # https://github.com/rancher/rancher/releases
rancher_path: "{{ home_path }}/rancher"
hostname: "hostname@domain.com"
bootstrap_password: "your-bootstrap-password"

